give @s[name="Arsey RC"] athos_avatars:arsey_rc_head_item
give @s[name="Atlaskes"] athos_avatars:atlaskes_head_item
give @s[name="Bigdog184382"] athos_avatars:bigdog184382_head_item
give @s[name="Calico Jacque"] athos_avatars:calico_jacque_head_item
give @s[name="CDN Hambone"] athos_avatars:cdn_hambone_head_item
give @s[name="Cragola"] athos_avatars:cragola_head_item
give @s[name="Damo8030"] athos_avatars:damo8030_head_item
give @s[name="Darth Angelo"] athos_avatars:darth_angelo_head_item
give @s[name="Dcstar36"] athos_avatars:dcstar36_head_item
give @s[name="DiatomicSloth19"] athos_avatars:diatomicsloth19_head_item
give @s[name="DingoZero"] athos_avatars:dingozero_head_item
give @s[name="EMPRESSTlTAN"] athos_avatars:empresstitan_head_item
give @s[name="FiremanKing 316"] athos_avatars:firemanking_316_head_item
give @s[name="FirstStorm5023"] athos_avatars:firststorm5023_head_item
give @s[name="Fr0mm1"] athos_avatars:fr0mm1_head_item
give @s[name="garthcp"] athos_avatars:garthcp_head_item
give @s[name="hillmanunited"] athos_avatars:hillmanunited_head_item
give @s[name="JangoBritt"] athos_avatars:jangobritt_head_item
give @s[name="JonahMacD"] athos_avatars:jonahmacd_head_item
give @s[name="Kailio 1980"] athos_avatars:kailio_1980_head_item
give @s[name="MastaTony"] athos_avatars:mastatony_head_item
give @s[name="Mids128"] athos_avatars:mids128_head_item
give @s[name="MxChlorine"] athos_avatars:mxchlorine_head_item
give @s[name="Ngarvi"] athos_avatars:ngarvi_head_item
give @s[name="NovaEmcarlo"] athos_avatars:novaemcarlo_head_item
give @s[name="OldCdnGamer"] athos_avatars:oldcdngamer_head_item
give @s[name="Purplelady1022"] athos_avatars:purplelady1022_head_item
give @s[name="Qwikstreet"] athos_avatars:qwikstreet_head_item
give @s[name="Raul Del Fuego"] athos_avatars:raul_del_fuego_head_item
give @s[name="Rezpint"] athos_avatars:rezpint_head_item
give @s[name="SFC Preston"] athos_avatars:sgtpreston2684_head_item
give @s[name="SolarYard1998"] athos_avatars:solaryard1998_head_item
give @s[name="Stesko9190"] athos_avatars:stesko_head_item
give @s[name="TCC_Segrub"] athos_avatars:tcc_segrub_head_item
give @s[name="Tellis042"] athos_avatars:tellis042_head_item
give @s[name="Tonystar73"] athos_avatars:tonystar73_head_item
give @s[name="VVangoWookie"] athos_avatars:vvangowookie_head_item
give @s[name="Wookieswife12"] athos_avatars:wookieswife12_head_item
give @s[name="xCGgamesx"] athos_avatars:xcggamesx_head_item
give @s[name="xRaistin"] athos_avatars:xraistin_head_item
give @s[name="acaito333"] athos_avatars:acaito333_head_item