execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=1}] run replaceitem entity @s slot.inventory 0 air
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=2}] run replaceitem entity @s slot.inventory 0 chicken 1
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=3}] run replaceitem entity @s slot.inventory 0 chicken 2
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=4}] run replaceitem entity @s slot.inventory 0 chicken 3
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=5}] run replaceitem entity @s slot.inventory 0 chicken 4
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=6}] run replaceitem entity @s slot.inventory 0 chicken 5
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=7}] run replaceitem entity @s slot.inventory 0 chicken 6
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=8}] run replaceitem entity @s slot.inventory 0 chicken 7
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=9}] run replaceitem entity @s slot.inventory 0 chicken 8
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=10}] run replaceitem entity @s slot.inventory 0 chicken 9
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=11}] run replaceitem entity @s slot.inventory 0 chicken 10
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=12}] run replaceitem entity @s slot.inventory 0 chicken 11
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=13}] run replaceitem entity @s slot.inventory 0 chicken 12
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=14}] run replaceitem entity @s slot.inventory 0 chicken 13
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=15}] run replaceitem entity @s slot.inventory 0 chicken 14
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=16}] run replaceitem entity @s slot.inventory 0 chicken 15
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=17}] run replaceitem entity @s slot.inventory 0 chicken 16
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=18}] run replaceitem entity @s slot.inventory 0 chicken 17
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=19}] run replaceitem entity @s slot.inventory 0 chicken 18
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=20}] run replaceitem entity @s slot.inventory 0 chicken 19
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=21}] run replaceitem entity @s slot.inventory 0 chicken 20
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=22}] run replaceitem entity @s slot.inventory 0 chicken 21
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=23}] run replaceitem entity @s slot.inventory 0 chicken 22
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=24}] run replaceitem entity @s slot.inventory 0 chicken 23
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=25}] run replaceitem entity @s slot.inventory 0 chicken 24
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=26}] run replaceitem entity @s slot.inventory 0 chicken 25
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=27}] run replaceitem entity @s slot.inventory 0 chicken 26
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=28}] run replaceitem entity @s slot.inventory 0 chicken 27
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=29}] run replaceitem entity @s slot.inventory 0 chicken 28
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=30}] run replaceitem entity @s slot.inventory 0 chicken 29
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=31}] run replaceitem entity @s slot.inventory 0 chicken 30
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=32}] run replaceitem entity @s slot.inventory 0 chicken 31
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=33}] run replaceitem entity @s slot.inventory 0 chicken 32
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=34}] run replaceitem entity @s slot.inventory 0 chicken 33
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=35}] run replaceitem entity @s slot.inventory 0 chicken 34
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=36}] run replaceitem entity @s slot.inventory 0 chicken 35
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=37}] run replaceitem entity @s slot.inventory 0 chicken 36
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=38}] run replaceitem entity @s slot.inventory 0 chicken 37
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=39}] run replaceitem entity @s slot.inventory 0 chicken 38
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=40}] run replaceitem entity @s slot.inventory 0 chicken 39
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=41}] run replaceitem entity @s slot.inventory 0 chicken 40
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=42}] run replaceitem entity @s slot.inventory 0 chicken 41
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=43}] run replaceitem entity @s slot.inventory 0 chicken 42
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=44}] run replaceitem entity @s slot.inventory 0 chicken 43
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=45}] run replaceitem entity @s slot.inventory 0 chicken 44
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=46}] run replaceitem entity @s slot.inventory 0 chicken 45
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=47}] run replaceitem entity @s slot.inventory 0 chicken 46
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=48}] run replaceitem entity @s slot.inventory 0 chicken 47
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=49}] run replaceitem entity @s slot.inventory 0 chicken 48
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=50}] run replaceitem entity @s slot.inventory 0 chicken 49
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=51}] run replaceitem entity @s slot.inventory 0 chicken 50
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=52}] run replaceitem entity @s slot.inventory 0 chicken 51
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=53}] run replaceitem entity @s slot.inventory 0 chicken 52
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=54}] run replaceitem entity @s slot.inventory 0 chicken 53
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=55}] run replaceitem entity @s slot.inventory 0 chicken 54
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=56}] run replaceitem entity @s slot.inventory 0 chicken 55
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=57}] run replaceitem entity @s slot.inventory 0 chicken 56
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=58}] run replaceitem entity @s slot.inventory 0 chicken 57
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=59}] run replaceitem entity @s slot.inventory 0 chicken 58
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=60}] run replaceitem entity @s slot.inventory 0 chicken 59
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=61}] run replaceitem entity @s slot.inventory 0 chicken 60
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=62}] run replaceitem entity @s slot.inventory 0 chicken 61
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=63}] run replaceitem entity @s slot.inventory 0 chicken 62
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=0,quantity=64}] run replaceitem entity @s slot.inventory 0 chicken 63

execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=1}] run replaceitem entity @s slot.inventory 0 air
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=2}] run replaceitem entity @s slot.inventory 0 porkchop 1
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=3}] run replaceitem entity @s slot.inventory 0 porkchop 2
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=4}] run replaceitem entity @s slot.inventory 0 porkchop 3
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=5}] run replaceitem entity @s slot.inventory 0 porkchop 4
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=6}] run replaceitem entity @s slot.inventory 0 porkchop 5
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=7}] run replaceitem entity @s slot.inventory 0 porkchop 6
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=8}] run replaceitem entity @s slot.inventory 0 porkchop 7
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=9}] run replaceitem entity @s slot.inventory 0 porkchop 8
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=10}] run replaceitem entity @s slot.inventory 0 porkchop 9
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=11}] run replaceitem entity @s slot.inventory 0 porkchop 10
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=12}] run replaceitem entity @s slot.inventory 0 porkchop 11
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=13}] run replaceitem entity @s slot.inventory 0 porkchop 12
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=14}] run replaceitem entity @s slot.inventory 0 porkchop 13
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=15}] run replaceitem entity @s slot.inventory 0 porkchop 14
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=16}] run replaceitem entity @s slot.inventory 0 porkchop 15
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=17}] run replaceitem entity @s slot.inventory 0 porkchop 16
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=18}] run replaceitem entity @s slot.inventory 0 porkchop 17
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=19}] run replaceitem entity @s slot.inventory 0 porkchop 18
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=20}] run replaceitem entity @s slot.inventory 0 porkchop 19
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=21}] run replaceitem entity @s slot.inventory 0 porkchop 20
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=22}] run replaceitem entity @s slot.inventory 0 porkchop 21
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=23}] run replaceitem entity @s slot.inventory 0 porkchop 22
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=24}] run replaceitem entity @s slot.inventory 0 porkchop 23
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=25}] run replaceitem entity @s slot.inventory 0 porkchop 24
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=26}] run replaceitem entity @s slot.inventory 0 porkchop 25
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=27}] run replaceitem entity @s slot.inventory 0 porkchop 26
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=28}] run replaceitem entity @s slot.inventory 0 porkchop 27
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=29}] run replaceitem entity @s slot.inventory 0 porkchop 28
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=30}] run replaceitem entity @s slot.inventory 0 porkchop 29
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=31}] run replaceitem entity @s slot.inventory 0 porkchop 30
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=32}] run replaceitem entity @s slot.inventory 0 porkchop 31
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=33}] run replaceitem entity @s slot.inventory 0 porkchop 32
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=34}] run replaceitem entity @s slot.inventory 0 porkchop 33
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=35}] run replaceitem entity @s slot.inventory 0 porkchop 34
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=36}] run replaceitem entity @s slot.inventory 0 porkchop 35
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=37}] run replaceitem entity @s slot.inventory 0 porkchop 36
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=38}] run replaceitem entity @s slot.inventory 0 porkchop 37
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=39}] run replaceitem entity @s slot.inventory 0 porkchop 38
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=40}] run replaceitem entity @s slot.inventory 0 porkchop 39
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=41}] run replaceitem entity @s slot.inventory 0 porkchop 40
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=42}] run replaceitem entity @s slot.inventory 0 porkchop 41
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=43}] run replaceitem entity @s slot.inventory 0 porkchop 42
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=44}] run replaceitem entity @s slot.inventory 0 porkchop 43
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=45}] run replaceitem entity @s slot.inventory 0 porkchop 44
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=46}] run replaceitem entity @s slot.inventory 0 porkchop 45
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=47}] run replaceitem entity @s slot.inventory 0 porkchop 46
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=48}] run replaceitem entity @s slot.inventory 0 porkchop 47
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=49}] run replaceitem entity @s slot.inventory 0 porkchop 48
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=50}] run replaceitem entity @s slot.inventory 0 porkchop 49
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=51}] run replaceitem entity @s slot.inventory 0 porkchop 50
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=52}] run replaceitem entity @s slot.inventory 0 porkchop 51
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=53}] run replaceitem entity @s slot.inventory 0 porkchop 52
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=54}] run replaceitem entity @s slot.inventory 0 porkchop 53
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=55}] run replaceitem entity @s slot.inventory 0 porkchop 54
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=56}] run replaceitem entity @s slot.inventory 0 porkchop 55
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=57}] run replaceitem entity @s slot.inventory 0 porkchop 56
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=58}] run replaceitem entity @s slot.inventory 0 porkchop 57
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=59}] run replaceitem entity @s slot.inventory 0 porkchop 58
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=60}] run replaceitem entity @s slot.inventory 0 porkchop 59
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=61}] run replaceitem entity @s slot.inventory 0 porkchop 60
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=62}] run replaceitem entity @s slot.inventory 0 porkchop 61
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=63}] run replaceitem entity @s slot.inventory 0 porkchop 62
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=0,quantity=64}] run replaceitem entity @s slot.inventory 0 porkchop 63

execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=1}] run replaceitem entity @s slot.inventory 0 air
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=2}] run replaceitem entity @s slot.inventory 0 beef 1
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=3}] run replaceitem entity @s slot.inventory 0 beef 2
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=4}] run replaceitem entity @s slot.inventory 0 beef 3
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=5}] run replaceitem entity @s slot.inventory 0 beef 4
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=6}] run replaceitem entity @s slot.inventory 0 beef 5
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=7}] run replaceitem entity @s slot.inventory 0 beef 6
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=8}] run replaceitem entity @s slot.inventory 0 beef 7
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=9}] run replaceitem entity @s slot.inventory 0 beef 8
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=10}] run replaceitem entity @s slot.inventory 0 beef 9
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=11}] run replaceitem entity @s slot.inventory 0 beef 10
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=12}] run replaceitem entity @s slot.inventory 0 beef 11
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=13}] run replaceitem entity @s slot.inventory 0 beef 12
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=14}] run replaceitem entity @s slot.inventory 0 beef 13
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=15}] run replaceitem entity @s slot.inventory 0 beef 14
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=16}] run replaceitem entity @s slot.inventory 0 beef 15
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=17}] run replaceitem entity @s slot.inventory 0 beef 16
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=18}] run replaceitem entity @s slot.inventory 0 beef 17
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=19}] run replaceitem entity @s slot.inventory 0 beef 18
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=20}] run replaceitem entity @s slot.inventory 0 beef 19
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=21}] run replaceitem entity @s slot.inventory 0 beef 20
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=22}] run replaceitem entity @s slot.inventory 0 beef 21
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=23}] run replaceitem entity @s slot.inventory 0 beef 22
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=24}] run replaceitem entity @s slot.inventory 0 beef 23
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=25}] run replaceitem entity @s slot.inventory 0 beef 24
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=26}] run replaceitem entity @s slot.inventory 0 beef 25
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=27}] run replaceitem entity @s slot.inventory 0 beef 26
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=28}] run replaceitem entity @s slot.inventory 0 beef 27
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=29}] run replaceitem entity @s slot.inventory 0 beef 28
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=30}] run replaceitem entity @s slot.inventory 0 beef 29
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=31}] run replaceitem entity @s slot.inventory 0 beef 30
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=32}] run replaceitem entity @s slot.inventory 0 beef 31
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=33}] run replaceitem entity @s slot.inventory 0 beef 32
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=34}] run replaceitem entity @s slot.inventory 0 beef 33
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=35}] run replaceitem entity @s slot.inventory 0 beef 34
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=36}] run replaceitem entity @s slot.inventory 0 beef 35
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=37}] run replaceitem entity @s slot.inventory 0 beef 36
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=38}] run replaceitem entity @s slot.inventory 0 beef 37
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=39}] run replaceitem entity @s slot.inventory 0 beef 38
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=40}] run replaceitem entity @s slot.inventory 0 beef 39
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=41}] run replaceitem entity @s slot.inventory 0 beef 40
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=42}] run replaceitem entity @s slot.inventory 0 beef 41
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=43}] run replaceitem entity @s slot.inventory 0 beef 42
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=44}] run replaceitem entity @s slot.inventory 0 beef 43
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=45}] run replaceitem entity @s slot.inventory 0 beef 44
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=46}] run replaceitem entity @s slot.inventory 0 beef 45
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=47}] run replaceitem entity @s slot.inventory 0 beef 46
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=48}] run replaceitem entity @s slot.inventory 0 beef 47
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=49}] run replaceitem entity @s slot.inventory 0 beef 48
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=50}] run replaceitem entity @s slot.inventory 0 beef 49
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=51}] run replaceitem entity @s slot.inventory 0 beef 50
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=52}] run replaceitem entity @s slot.inventory 0 beef 51
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=53}] run replaceitem entity @s slot.inventory 0 beef 52
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=54}] run replaceitem entity @s slot.inventory 0 beef 53
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=55}] run replaceitem entity @s slot.inventory 0 beef 54
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=56}] run replaceitem entity @s slot.inventory 0 beef 55
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=57}] run replaceitem entity @s slot.inventory 0 beef 56
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=58}] run replaceitem entity @s slot.inventory 0 beef 57
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=59}] run replaceitem entity @s slot.inventory 0 beef 58
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=60}] run replaceitem entity @s slot.inventory 0 beef 59
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=61}] run replaceitem entity @s slot.inventory 0 beef 60
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=62}] run replaceitem entity @s slot.inventory 0 beef 61
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=63}] run replaceitem entity @s slot.inventory 0 beef 62
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=0,quantity=64}] run replaceitem entity @s slot.inventory 0 beef 63

execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=1}] run replaceitem entity @s slot.inventory 0 air
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=2}] run replaceitem entity @s slot.inventory 0 mutton 1
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=3}] run replaceitem entity @s slot.inventory 0 mutton 2
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=4}] run replaceitem entity @s slot.inventory 0 mutton 3
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=5}] run replaceitem entity @s slot.inventory 0 mutton 4
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=6}] run replaceitem entity @s slot.inventory 0 mutton 5
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=7}] run replaceitem entity @s slot.inventory 0 mutton 6
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=8}] run replaceitem entity @s slot.inventory 0 mutton 7
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=9}] run replaceitem entity @s slot.inventory 0 mutton 8
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=10}] run replaceitem entity @s slot.inventory 0 mutton 9
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=11}] run replaceitem entity @s slot.inventory 0 mutton 10
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=12}] run replaceitem entity @s slot.inventory 0 mutton 11
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=13}] run replaceitem entity @s slot.inventory 0 mutton 12
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=14}] run replaceitem entity @s slot.inventory 0 mutton 13
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=15}] run replaceitem entity @s slot.inventory 0 mutton 14
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=16}] run replaceitem entity @s slot.inventory 0 mutton 15
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=17}] run replaceitem entity @s slot.inventory 0 mutton 16
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=18}] run replaceitem entity @s slot.inventory 0 mutton 17
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=19}] run replaceitem entity @s slot.inventory 0 mutton 18
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=20}] run replaceitem entity @s slot.inventory 0 mutton 19
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=21}] run replaceitem entity @s slot.inventory 0 mutton 20
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=22}] run replaceitem entity @s slot.inventory 0 mutton 21
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=23}] run replaceitem entity @s slot.inventory 0 mutton 22
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=24}] run replaceitem entity @s slot.inventory 0 mutton 23
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=25}] run replaceitem entity @s slot.inventory 0 mutton 24
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=26}] run replaceitem entity @s slot.inventory 0 mutton 25
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=27}] run replaceitem entity @s slot.inventory 0 mutton 26
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=28}] run replaceitem entity @s slot.inventory 0 mutton 27
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=29}] run replaceitem entity @s slot.inventory 0 mutton 28
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=30}] run replaceitem entity @s slot.inventory 0 mutton 29
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=31}] run replaceitem entity @s slot.inventory 0 mutton 30
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=32}] run replaceitem entity @s slot.inventory 0 mutton 31
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=33}] run replaceitem entity @s slot.inventory 0 mutton 32
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=34}] run replaceitem entity @s slot.inventory 0 mutton 33
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=35}] run replaceitem entity @s slot.inventory 0 mutton 34
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=36}] run replaceitem entity @s slot.inventory 0 mutton 35
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=37}] run replaceitem entity @s slot.inventory 0 mutton 36
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=38}] run replaceitem entity @s slot.inventory 0 mutton 37
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=39}] run replaceitem entity @s slot.inventory 0 mutton 38
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=40}] run replaceitem entity @s slot.inventory 0 mutton 39
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=41}] run replaceitem entity @s slot.inventory 0 mutton 40
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=42}] run replaceitem entity @s slot.inventory 0 mutton 41
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=43}] run replaceitem entity @s slot.inventory 0 mutton 42
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=44}] run replaceitem entity @s slot.inventory 0 mutton 43
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=45}] run replaceitem entity @s slot.inventory 0 mutton 44
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=46}] run replaceitem entity @s slot.inventory 0 mutton 45
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=47}] run replaceitem entity @s slot.inventory 0 mutton 46
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=48}] run replaceitem entity @s slot.inventory 0 mutton 47
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=49}] run replaceitem entity @s slot.inventory 0 mutton 48
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=50}] run replaceitem entity @s slot.inventory 0 mutton 49
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=51}] run replaceitem entity @s slot.inventory 0 mutton 50
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=52}] run replaceitem entity @s slot.inventory 0 mutton 51
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=53}] run replaceitem entity @s slot.inventory 0 mutton 52
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=54}] run replaceitem entity @s slot.inventory 0 mutton 53
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=55}] run replaceitem entity @s slot.inventory 0 mutton 54
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=56}] run replaceitem entity @s slot.inventory 0 mutton 55
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=57}] run replaceitem entity @s slot.inventory 0 mutton 56
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=58}] run replaceitem entity @s slot.inventory 0 mutton 57
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=59}] run replaceitem entity @s slot.inventory 0 mutton 58
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=60}] run replaceitem entity @s slot.inventory 0 mutton 59
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=61}] run replaceitem entity @s slot.inventory 0 mutton 60
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=62}] run replaceitem entity @s slot.inventory 0 mutton 61
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=63}] run replaceitem entity @s slot.inventory 0 mutton 62
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=0,quantity=64}] run replaceitem entity @s slot.inventory 0 mutton 63

execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=1}] run replaceitem entity @s slot.inventory 0 air
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=2}] run replaceitem entity @s slot.inventory 0 rabbit 1
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=3}] run replaceitem entity @s slot.inventory 0 rabbit 2
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=4}] run replaceitem entity @s slot.inventory 0 rabbit 3
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=5}] run replaceitem entity @s slot.inventory 0 rabbit 4
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=6}] run replaceitem entity @s slot.inventory 0 rabbit 5
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=7}] run replaceitem entity @s slot.inventory 0 rabbit 6
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=8}] run replaceitem entity @s slot.inventory 0 rabbit 7
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=9}] run replaceitem entity @s slot.inventory 0 rabbit 8
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=10}] run replaceitem entity @s slot.inventory 0 rabbit 9
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=11}] run replaceitem entity @s slot.inventory 0 rabbit 10
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=12}] run replaceitem entity @s slot.inventory 0 rabbit 11
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=13}] run replaceitem entity @s slot.inventory 0 rabbit 12
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=14}] run replaceitem entity @s slot.inventory 0 rabbit 13
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=15}] run replaceitem entity @s slot.inventory 0 rabbit 14
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=16}] run replaceitem entity @s slot.inventory 0 rabbit 15
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=17}] run replaceitem entity @s slot.inventory 0 rabbit 16
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=18}] run replaceitem entity @s slot.inventory 0 rabbit 17
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=19}] run replaceitem entity @s slot.inventory 0 rabbit 18
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=20}] run replaceitem entity @s slot.inventory 0 rabbit 19
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=21}] run replaceitem entity @s slot.inventory 0 rabbit 20
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=22}] run replaceitem entity @s slot.inventory 0 rabbit 21
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=23}] run replaceitem entity @s slot.inventory 0 rabbit 22
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=24}] run replaceitem entity @s slot.inventory 0 rabbit 23
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=25}] run replaceitem entity @s slot.inventory 0 rabbit 24
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=26}] run replaceitem entity @s slot.inventory 0 rabbit 25
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=27}] run replaceitem entity @s slot.inventory 0 rabbit 26
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=28}] run replaceitem entity @s slot.inventory 0 rabbit 27
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=29}] run replaceitem entity @s slot.inventory 0 rabbit 28
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=30}] run replaceitem entity @s slot.inventory 0 rabbit 29
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=31}] run replaceitem entity @s slot.inventory 0 rabbit 30
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=32}] run replaceitem entity @s slot.inventory 0 rabbit 31
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=33}] run replaceitem entity @s slot.inventory 0 rabbit 32
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=34}] run replaceitem entity @s slot.inventory 0 rabbit 33
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=35}] run replaceitem entity @s slot.inventory 0 rabbit 34
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=36}] run replaceitem entity @s slot.inventory 0 rabbit 35
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=37}] run replaceitem entity @s slot.inventory 0 rabbit 36
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=38}] run replaceitem entity @s slot.inventory 0 rabbit 37
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=39}] run replaceitem entity @s slot.inventory 0 rabbit 38
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=40}] run replaceitem entity @s slot.inventory 0 rabbit 39
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=41}] run replaceitem entity @s slot.inventory 0 rabbit 40
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=42}] run replaceitem entity @s slot.inventory 0 rabbit 41
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=43}] run replaceitem entity @s slot.inventory 0 rabbit 42
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=44}] run replaceitem entity @s slot.inventory 0 rabbit 43
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=45}] run replaceitem entity @s slot.inventory 0 rabbit 44
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=46}] run replaceitem entity @s slot.inventory 0 rabbit 45
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=47}] run replaceitem entity @s slot.inventory 0 rabbit 46
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=48}] run replaceitem entity @s slot.inventory 0 rabbit 47
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=49}] run replaceitem entity @s slot.inventory 0 rabbit 48
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=50}] run replaceitem entity @s slot.inventory 0 rabbit 49
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=51}] run replaceitem entity @s slot.inventory 0 rabbit 50
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=52}] run replaceitem entity @s slot.inventory 0 rabbit 51
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=53}] run replaceitem entity @s slot.inventory 0 rabbit 52
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=54}] run replaceitem entity @s slot.inventory 0 rabbit 53
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=55}] run replaceitem entity @s slot.inventory 0 rabbit 54
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=56}] run replaceitem entity @s slot.inventory 0 rabbit 55
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=57}] run replaceitem entity @s slot.inventory 0 rabbit 56
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=58}] run replaceitem entity @s slot.inventory 0 rabbit 57
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=59}] run replaceitem entity @s slot.inventory 0 rabbit 58
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=60}] run replaceitem entity @s slot.inventory 0 rabbit 59
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=61}] run replaceitem entity @s slot.inventory 0 rabbit 60
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=62}] run replaceitem entity @s slot.inventory 0 rabbit 61
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=63}] run replaceitem entity @s slot.inventory 0 rabbit 62
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=0,quantity=64}] run replaceitem entity @s slot.inventory 0 rabbit 63

execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=1}] run replaceitem entity @s slot.inventory 0 air
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=2}] run replaceitem entity @s slot.inventory 0 cod 1
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=3}] run replaceitem entity @s slot.inventory 0 cod 2
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=4}] run replaceitem entity @s slot.inventory 0 cod 3
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=5}] run replaceitem entity @s slot.inventory 0 cod 4
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=6}] run replaceitem entity @s slot.inventory 0 cod 5
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=7}] run replaceitem entity @s slot.inventory 0 cod 6
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=8}] run replaceitem entity @s slot.inventory 0 cod 7
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=9}] run replaceitem entity @s slot.inventory 0 cod 8
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=10}] run replaceitem entity @s slot.inventory 0 cod 9
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=11}] run replaceitem entity @s slot.inventory 0 cod 10
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=12}] run replaceitem entity @s slot.inventory 0 cod 11
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=13}] run replaceitem entity @s slot.inventory 0 cod 12
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=14}] run replaceitem entity @s slot.inventory 0 cod 13
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=15}] run replaceitem entity @s slot.inventory 0 cod 14
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=16}] run replaceitem entity @s slot.inventory 0 cod 15
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=17}] run replaceitem entity @s slot.inventory 0 cod 16
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=18}] run replaceitem entity @s slot.inventory 0 cod 17
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=19}] run replaceitem entity @s slot.inventory 0 cod 18
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=20}] run replaceitem entity @s slot.inventory 0 cod 19
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=21}] run replaceitem entity @s slot.inventory 0 cod 20
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=22}] run replaceitem entity @s slot.inventory 0 cod 21
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=23}] run replaceitem entity @s slot.inventory 0 cod 22
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=24}] run replaceitem entity @s slot.inventory 0 cod 23
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=25}] run replaceitem entity @s slot.inventory 0 cod 24
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=26}] run replaceitem entity @s slot.inventory 0 cod 25
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=27}] run replaceitem entity @s slot.inventory 0 cod 26
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=28}] run replaceitem entity @s slot.inventory 0 cod 27
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=29}] run replaceitem entity @s slot.inventory 0 cod 28
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=30}] run replaceitem entity @s slot.inventory 0 cod 29
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=31}] run replaceitem entity @s slot.inventory 0 cod 30
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=32}] run replaceitem entity @s slot.inventory 0 cod 31
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=33}] run replaceitem entity @s slot.inventory 0 cod 32
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=34}] run replaceitem entity @s slot.inventory 0 cod 33
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=35}] run replaceitem entity @s slot.inventory 0 cod 34
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=36}] run replaceitem entity @s slot.inventory 0 cod 35
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=37}] run replaceitem entity @s slot.inventory 0 cod 36
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=38}] run replaceitem entity @s slot.inventory 0 cod 37
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=39}] run replaceitem entity @s slot.inventory 0 cod 38
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=40}] run replaceitem entity @s slot.inventory 0 cod 39
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=41}] run replaceitem entity @s slot.inventory 0 cod 40
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=42}] run replaceitem entity @s slot.inventory 0 cod 41
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=43}] run replaceitem entity @s slot.inventory 0 cod 42
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=44}] run replaceitem entity @s slot.inventory 0 cod 43
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=45}] run replaceitem entity @s slot.inventory 0 cod 44
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=46}] run replaceitem entity @s slot.inventory 0 cod 45
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=47}] run replaceitem entity @s slot.inventory 0 cod 46
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=48}] run replaceitem entity @s slot.inventory 0 cod 47
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=49}] run replaceitem entity @s slot.inventory 0 cod 48
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=50}] run replaceitem entity @s slot.inventory 0 cod 49
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=51}] run replaceitem entity @s slot.inventory 0 cod 50
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=52}] run replaceitem entity @s slot.inventory 0 cod 51
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=53}] run replaceitem entity @s slot.inventory 0 cod 52
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=54}] run replaceitem entity @s slot.inventory 0 cod 53
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=55}] run replaceitem entity @s slot.inventory 0 cod 54
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=56}] run replaceitem entity @s slot.inventory 0 cod 55
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=57}] run replaceitem entity @s slot.inventory 0 cod 56
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=58}] run replaceitem entity @s slot.inventory 0 cod 57
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=59}] run replaceitem entity @s slot.inventory 0 cod 58
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=60}] run replaceitem entity @s slot.inventory 0 cod 59
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=61}] run replaceitem entity @s slot.inventory 0 cod 60
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=62}] run replaceitem entity @s slot.inventory 0 cod 61
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=63}] run replaceitem entity @s slot.inventory 0 cod 62
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=0,quantity=64}] run replaceitem entity @s slot.inventory 0 cod 63

execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=1}] run replaceitem entity @s slot.inventory 0 air
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=2}] run replaceitem entity @s slot.inventory 0 salmon 1
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=3}] run replaceitem entity @s slot.inventory 0 salmon 2
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=4}] run replaceitem entity @s slot.inventory 0 salmon 3
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=5}] run replaceitem entity @s slot.inventory 0 salmon 4
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=6}] run replaceitem entity @s slot.inventory 0 salmon 5
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=7}] run replaceitem entity @s slot.inventory 0 salmon 6
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=8}] run replaceitem entity @s slot.inventory 0 salmon 7
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=9}] run replaceitem entity @s slot.inventory 0 salmon 8
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=10}] run replaceitem entity @s slot.inventory 0 salmon 9
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=11}] run replaceitem entity @s slot.inventory 0 salmon 10
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=12}] run replaceitem entity @s slot.inventory 0 salmon 11
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=13}] run replaceitem entity @s slot.inventory 0 salmon 12
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=14}] run replaceitem entity @s slot.inventory 0 salmon 13
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=15}] run replaceitem entity @s slot.inventory 0 salmon 14
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=16}] run replaceitem entity @s slot.inventory 0 salmon 15
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=17}] run replaceitem entity @s slot.inventory 0 salmon 16
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=18}] run replaceitem entity @s slot.inventory 0 salmon 17
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=19}] run replaceitem entity @s slot.inventory 0 salmon 18
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=20}] run replaceitem entity @s slot.inventory 0 salmon 19
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=21}] run replaceitem entity @s slot.inventory 0 salmon 20
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=22}] run replaceitem entity @s slot.inventory 0 salmon 21
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=23}] run replaceitem entity @s slot.inventory 0 salmon 22
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=24}] run replaceitem entity @s slot.inventory 0 salmon 23
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=25}] run replaceitem entity @s slot.inventory 0 salmon 24
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=26}] run replaceitem entity @s slot.inventory 0 salmon 25
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=27}] run replaceitem entity @s slot.inventory 0 salmon 26
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=28}] run replaceitem entity @s slot.inventory 0 salmon 27
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=29}] run replaceitem entity @s slot.inventory 0 salmon 28
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=30}] run replaceitem entity @s slot.inventory 0 salmon 29
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=31}] run replaceitem entity @s slot.inventory 0 salmon 30
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=32}] run replaceitem entity @s slot.inventory 0 salmon 31
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=33}] run replaceitem entity @s slot.inventory 0 salmon 32
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=34}] run replaceitem entity @s slot.inventory 0 salmon 33
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=35}] run replaceitem entity @s slot.inventory 0 salmon 34
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=36}] run replaceitem entity @s slot.inventory 0 salmon 35
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=37}] run replaceitem entity @s slot.inventory 0 salmon 36
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=38}] run replaceitem entity @s slot.inventory 0 salmon 37
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=39}] run replaceitem entity @s slot.inventory 0 salmon 38
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=40}] run replaceitem entity @s slot.inventory 0 salmon 39
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=41}] run replaceitem entity @s slot.inventory 0 salmon 40
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=42}] run replaceitem entity @s slot.inventory 0 salmon 41
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=43}] run replaceitem entity @s slot.inventory 0 salmon 42
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=44}] run replaceitem entity @s slot.inventory 0 salmon 43
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=45}] run replaceitem entity @s slot.inventory 0 salmon 44
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=46}] run replaceitem entity @s slot.inventory 0 salmon 45
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=47}] run replaceitem entity @s slot.inventory 0 salmon 46
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=48}] run replaceitem entity @s slot.inventory 0 salmon 47
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=49}] run replaceitem entity @s slot.inventory 0 salmon 48
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=50}] run replaceitem entity @s slot.inventory 0 salmon 49
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=51}] run replaceitem entity @s slot.inventory 0 salmon 50
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=52}] run replaceitem entity @s slot.inventory 0 salmon 51
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=53}] run replaceitem entity @s slot.inventory 0 salmon 52
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=54}] run replaceitem entity @s slot.inventory 0 salmon 53
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=55}] run replaceitem entity @s slot.inventory 0 salmon 54
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=56}] run replaceitem entity @s slot.inventory 0 salmon 55
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=57}] run replaceitem entity @s slot.inventory 0 salmon 56
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=58}] run replaceitem entity @s slot.inventory 0 salmon 57
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=59}] run replaceitem entity @s slot.inventory 0 salmon 58
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=60}] run replaceitem entity @s slot.inventory 0 salmon 59
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=61}] run replaceitem entity @s slot.inventory 0 salmon 60
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=62}] run replaceitem entity @s slot.inventory 0 salmon 61
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=63}] run replaceitem entity @s slot.inventory 0 salmon 62
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=0,quantity=64}] run replaceitem entity @s slot.inventory 0 salmon 63