execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=1}] run replaceitem entity @s slot.inventory 4 air
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=2}] run replaceitem entity @s slot.inventory 4 chicken 1
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=3}] run replaceitem entity @s slot.inventory 4 chicken 2
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=4}] run replaceitem entity @s slot.inventory 4 chicken 3
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=5}] run replaceitem entity @s slot.inventory 4 chicken 4
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=6}] run replaceitem entity @s slot.inventory 4 chicken 5
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=7}] run replaceitem entity @s slot.inventory 4 chicken 6
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=8}] run replaceitem entity @s slot.inventory 4 chicken 7
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=9}] run replaceitem entity @s slot.inventory 4 chicken 8
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=10}] run replaceitem entity @s slot.inventory 4 chicken 9
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=11}] run replaceitem entity @s slot.inventory 4 chicken 10
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=12}] run replaceitem entity @s slot.inventory 4 chicken 11
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=13}] run replaceitem entity @s slot.inventory 4 chicken 12
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=14}] run replaceitem entity @s slot.inventory 4 chicken 13
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=15}] run replaceitem entity @s slot.inventory 4 chicken 14
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=16}] run replaceitem entity @s slot.inventory 4 chicken 15
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=17}] run replaceitem entity @s slot.inventory 4 chicken 16
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=18}] run replaceitem entity @s slot.inventory 4 chicken 17
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=19}] run replaceitem entity @s slot.inventory 4 chicken 18
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=20}] run replaceitem entity @s slot.inventory 4 chicken 19
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=21}] run replaceitem entity @s slot.inventory 4 chicken 20
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=22}] run replaceitem entity @s slot.inventory 4 chicken 21
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=23}] run replaceitem entity @s slot.inventory 4 chicken 22
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=24}] run replaceitem entity @s slot.inventory 4 chicken 23
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=25}] run replaceitem entity @s slot.inventory 4 chicken 24
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=26}] run replaceitem entity @s slot.inventory 4 chicken 25
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=27}] run replaceitem entity @s slot.inventory 4 chicken 26
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=28}] run replaceitem entity @s slot.inventory 4 chicken 27
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=29}] run replaceitem entity @s slot.inventory 4 chicken 28
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=30}] run replaceitem entity @s slot.inventory 4 chicken 29
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=31}] run replaceitem entity @s slot.inventory 4 chicken 30
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=32}] run replaceitem entity @s slot.inventory 4 chicken 31
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=33}] run replaceitem entity @s slot.inventory 4 chicken 32
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=34}] run replaceitem entity @s slot.inventory 4 chicken 33
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=35}] run replaceitem entity @s slot.inventory 4 chicken 34
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=36}] run replaceitem entity @s slot.inventory 4 chicken 35
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=37}] run replaceitem entity @s slot.inventory 4 chicken 36
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=38}] run replaceitem entity @s slot.inventory 4 chicken 37
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=39}] run replaceitem entity @s slot.inventory 4 chicken 38
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=40}] run replaceitem entity @s slot.inventory 4 chicken 39
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=41}] run replaceitem entity @s slot.inventory 4 chicken 40
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=42}] run replaceitem entity @s slot.inventory 4 chicken 41
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=43}] run replaceitem entity @s slot.inventory 4 chicken 42
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=44}] run replaceitem entity @s slot.inventory 4 chicken 43
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=45}] run replaceitem entity @s slot.inventory 4 chicken 44
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=46}] run replaceitem entity @s slot.inventory 4 chicken 45
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=47}] run replaceitem entity @s slot.inventory 4 chicken 46
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=48}] run replaceitem entity @s slot.inventory 4 chicken 47
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=49}] run replaceitem entity @s slot.inventory 4 chicken 48
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=50}] run replaceitem entity @s slot.inventory 4 chicken 49
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=51}] run replaceitem entity @s slot.inventory 4 chicken 50
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=52}] run replaceitem entity @s slot.inventory 4 chicken 51
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=53}] run replaceitem entity @s slot.inventory 4 chicken 52
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=54}] run replaceitem entity @s slot.inventory 4 chicken 53
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=55}] run replaceitem entity @s slot.inventory 4 chicken 54
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=56}] run replaceitem entity @s slot.inventory 4 chicken 55
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=57}] run replaceitem entity @s slot.inventory 4 chicken 56
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=58}] run replaceitem entity @s slot.inventory 4 chicken 57
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=59}] run replaceitem entity @s slot.inventory 4 chicken 58
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=60}] run replaceitem entity @s slot.inventory 4 chicken 59
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=61}] run replaceitem entity @s slot.inventory 4 chicken 60
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=62}] run replaceitem entity @s slot.inventory 4 chicken 61
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=63}] run replaceitem entity @s slot.inventory 4 chicken 62
execute at @s if entity @s[hasitem={item=chicken,location=slot.inventory,slot=4,quantity=64}] run replaceitem entity @s slot.inventory 4 chicken 63

execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=1}] run replaceitem entity @s slot.inventory 4 air
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=2}] run replaceitem entity @s slot.inventory 4 porkchop 1
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=3}] run replaceitem entity @s slot.inventory 4 porkchop 2
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=4}] run replaceitem entity @s slot.inventory 4 porkchop 3
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=5}] run replaceitem entity @s slot.inventory 4 porkchop 4
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=6}] run replaceitem entity @s slot.inventory 4 porkchop 5
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=7}] run replaceitem entity @s slot.inventory 4 porkchop 6
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=8}] run replaceitem entity @s slot.inventory 4 porkchop 7
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=9}] run replaceitem entity @s slot.inventory 4 porkchop 8
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=10}] run replaceitem entity @s slot.inventory 4 porkchop 9
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=11}] run replaceitem entity @s slot.inventory 4 porkchop 10
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=12}] run replaceitem entity @s slot.inventory 4 porkchop 11
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=13}] run replaceitem entity @s slot.inventory 4 porkchop 12
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=14}] run replaceitem entity @s slot.inventory 4 porkchop 13
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=15}] run replaceitem entity @s slot.inventory 4 porkchop 14
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=16}] run replaceitem entity @s slot.inventory 4 porkchop 15
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=17}] run replaceitem entity @s slot.inventory 4 porkchop 16
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=18}] run replaceitem entity @s slot.inventory 4 porkchop 17
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=19}] run replaceitem entity @s slot.inventory 4 porkchop 18
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=20}] run replaceitem entity @s slot.inventory 4 porkchop 19
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=21}] run replaceitem entity @s slot.inventory 4 porkchop 20
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=22}] run replaceitem entity @s slot.inventory 4 porkchop 21
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=23}] run replaceitem entity @s slot.inventory 4 porkchop 22
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=24}] run replaceitem entity @s slot.inventory 4 porkchop 23
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=25}] run replaceitem entity @s slot.inventory 4 porkchop 24
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=26}] run replaceitem entity @s slot.inventory 4 porkchop 25
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=27}] run replaceitem entity @s slot.inventory 4 porkchop 26
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=28}] run replaceitem entity @s slot.inventory 4 porkchop 27
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=29}] run replaceitem entity @s slot.inventory 4 porkchop 28
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=30}] run replaceitem entity @s slot.inventory 4 porkchop 29
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=31}] run replaceitem entity @s slot.inventory 4 porkchop 30
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=32}] run replaceitem entity @s slot.inventory 4 porkchop 31
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=33}] run replaceitem entity @s slot.inventory 4 porkchop 32
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=34}] run replaceitem entity @s slot.inventory 4 porkchop 33
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=35}] run replaceitem entity @s slot.inventory 4 porkchop 34
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=36}] run replaceitem entity @s slot.inventory 4 porkchop 35
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=37}] run replaceitem entity @s slot.inventory 4 porkchop 36
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=38}] run replaceitem entity @s slot.inventory 4 porkchop 37
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=39}] run replaceitem entity @s slot.inventory 4 porkchop 38
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=40}] run replaceitem entity @s slot.inventory 4 porkchop 39
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=41}] run replaceitem entity @s slot.inventory 4 porkchop 40
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=42}] run replaceitem entity @s slot.inventory 4 porkchop 41
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=43}] run replaceitem entity @s slot.inventory 4 porkchop 42
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=44}] run replaceitem entity @s slot.inventory 4 porkchop 43
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=45}] run replaceitem entity @s slot.inventory 4 porkchop 44
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=46}] run replaceitem entity @s slot.inventory 4 porkchop 45
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=47}] run replaceitem entity @s slot.inventory 4 porkchop 46
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=48}] run replaceitem entity @s slot.inventory 4 porkchop 47
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=49}] run replaceitem entity @s slot.inventory 4 porkchop 48
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=50}] run replaceitem entity @s slot.inventory 4 porkchop 49
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=51}] run replaceitem entity @s slot.inventory 4 porkchop 50
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=52}] run replaceitem entity @s slot.inventory 4 porkchop 51
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=53}] run replaceitem entity @s slot.inventory 4 porkchop 52
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=54}] run replaceitem entity @s slot.inventory 4 porkchop 53
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=55}] run replaceitem entity @s slot.inventory 4 porkchop 54
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=56}] run replaceitem entity @s slot.inventory 4 porkchop 55
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=57}] run replaceitem entity @s slot.inventory 4 porkchop 56
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=58}] run replaceitem entity @s slot.inventory 4 porkchop 57
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=59}] run replaceitem entity @s slot.inventory 4 porkchop 58
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=60}] run replaceitem entity @s slot.inventory 4 porkchop 59
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=61}] run replaceitem entity @s slot.inventory 4 porkchop 60
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=62}] run replaceitem entity @s slot.inventory 4 porkchop 61
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=63}] run replaceitem entity @s slot.inventory 4 porkchop 62
execute at @s if entity @s[hasitem={item=porkchop,location=slot.inventory,slot=4,quantity=64}] run replaceitem entity @s slot.inventory 4 porkchop 63

execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=1}] run replaceitem entity @s slot.inventory 4 air
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=2}] run replaceitem entity @s slot.inventory 4 beef 1
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=3}] run replaceitem entity @s slot.inventory 4 beef 2
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=4}] run replaceitem entity @s slot.inventory 4 beef 3
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=5}] run replaceitem entity @s slot.inventory 4 beef 4
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=6}] run replaceitem entity @s slot.inventory 4 beef 5
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=7}] run replaceitem entity @s slot.inventory 4 beef 6
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=8}] run replaceitem entity @s slot.inventory 4 beef 7
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=9}] run replaceitem entity @s slot.inventory 4 beef 8
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=10}] run replaceitem entity @s slot.inventory 4 beef 9
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=11}] run replaceitem entity @s slot.inventory 4 beef 10
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=12}] run replaceitem entity @s slot.inventory 4 beef 11
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=13}] run replaceitem entity @s slot.inventory 4 beef 12
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=14}] run replaceitem entity @s slot.inventory 4 beef 13
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=15}] run replaceitem entity @s slot.inventory 4 beef 14
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=16}] run replaceitem entity @s slot.inventory 4 beef 15
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=17}] run replaceitem entity @s slot.inventory 4 beef 16
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=18}] run replaceitem entity @s slot.inventory 4 beef 17
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=19}] run replaceitem entity @s slot.inventory 4 beef 18
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=20}] run replaceitem entity @s slot.inventory 4 beef 19
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=21}] run replaceitem entity @s slot.inventory 4 beef 20
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=22}] run replaceitem entity @s slot.inventory 4 beef 21
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=23}] run replaceitem entity @s slot.inventory 4 beef 22
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=24}] run replaceitem entity @s slot.inventory 4 beef 23
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=25}] run replaceitem entity @s slot.inventory 4 beef 24
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=26}] run replaceitem entity @s slot.inventory 4 beef 25
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=27}] run replaceitem entity @s slot.inventory 4 beef 26
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=28}] run replaceitem entity @s slot.inventory 4 beef 27
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=29}] run replaceitem entity @s slot.inventory 4 beef 28
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=30}] run replaceitem entity @s slot.inventory 4 beef 29
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=31}] run replaceitem entity @s slot.inventory 4 beef 30
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=32}] run replaceitem entity @s slot.inventory 4 beef 31
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=33}] run replaceitem entity @s slot.inventory 4 beef 32
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=34}] run replaceitem entity @s slot.inventory 4 beef 33
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=35}] run replaceitem entity @s slot.inventory 4 beef 34
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=36}] run replaceitem entity @s slot.inventory 4 beef 35
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=37}] run replaceitem entity @s slot.inventory 4 beef 36
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=38}] run replaceitem entity @s slot.inventory 4 beef 37
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=39}] run replaceitem entity @s slot.inventory 4 beef 38
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=40}] run replaceitem entity @s slot.inventory 4 beef 39
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=41}] run replaceitem entity @s slot.inventory 4 beef 40
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=42}] run replaceitem entity @s slot.inventory 4 beef 41
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=43}] run replaceitem entity @s slot.inventory 4 beef 42
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=44}] run replaceitem entity @s slot.inventory 4 beef 43
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=45}] run replaceitem entity @s slot.inventory 4 beef 44
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=46}] run replaceitem entity @s slot.inventory 4 beef 45
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=47}] run replaceitem entity @s slot.inventory 4 beef 46
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=48}] run replaceitem entity @s slot.inventory 4 beef 47
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=49}] run replaceitem entity @s slot.inventory 4 beef 48
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=50}] run replaceitem entity @s slot.inventory 4 beef 49
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=51}] run replaceitem entity @s slot.inventory 4 beef 50
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=52}] run replaceitem entity @s slot.inventory 4 beef 51
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=53}] run replaceitem entity @s slot.inventory 4 beef 52
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=54}] run replaceitem entity @s slot.inventory 4 beef 53
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=55}] run replaceitem entity @s slot.inventory 4 beef 54
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=56}] run replaceitem entity @s slot.inventory 4 beef 55
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=57}] run replaceitem entity @s slot.inventory 4 beef 56
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=58}] run replaceitem entity @s slot.inventory 4 beef 57
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=59}] run replaceitem entity @s slot.inventory 4 beef 58
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=60}] run replaceitem entity @s slot.inventory 4 beef 59
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=61}] run replaceitem entity @s slot.inventory 4 beef 60
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=62}] run replaceitem entity @s slot.inventory 4 beef 61
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=63}] run replaceitem entity @s slot.inventory 4 beef 62
execute at @s if entity @s[hasitem={item=beef,location=slot.inventory,slot=4,quantity=64}] run replaceitem entity @s slot.inventory 4 beef 63

execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=1}] run replaceitem entity @s slot.inventory 4 air
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=2}] run replaceitem entity @s slot.inventory 4 mutton 1
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=3}] run replaceitem entity @s slot.inventory 4 mutton 2
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=4}] run replaceitem entity @s slot.inventory 4 mutton 3
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=5}] run replaceitem entity @s slot.inventory 4 mutton 4
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=6}] run replaceitem entity @s slot.inventory 4 mutton 5
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=7}] run replaceitem entity @s slot.inventory 4 mutton 6
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=8}] run replaceitem entity @s slot.inventory 4 mutton 7
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=9}] run replaceitem entity @s slot.inventory 4 mutton 8
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=10}] run replaceitem entity @s slot.inventory 4 mutton 9
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=11}] run replaceitem entity @s slot.inventory 4 mutton 10
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=12}] run replaceitem entity @s slot.inventory 4 mutton 11
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=13}] run replaceitem entity @s slot.inventory 4 mutton 12
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=14}] run replaceitem entity @s slot.inventory 4 mutton 13
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=15}] run replaceitem entity @s slot.inventory 4 mutton 14
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=16}] run replaceitem entity @s slot.inventory 4 mutton 15
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=17}] run replaceitem entity @s slot.inventory 4 mutton 16
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=18}] run replaceitem entity @s slot.inventory 4 mutton 17
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=19}] run replaceitem entity @s slot.inventory 4 mutton 18
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=20}] run replaceitem entity @s slot.inventory 4 mutton 19
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=21}] run replaceitem entity @s slot.inventory 4 mutton 20
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=22}] run replaceitem entity @s slot.inventory 4 mutton 21
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=23}] run replaceitem entity @s slot.inventory 4 mutton 22
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=24}] run replaceitem entity @s slot.inventory 4 mutton 23
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=25}] run replaceitem entity @s slot.inventory 4 mutton 24
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=26}] run replaceitem entity @s slot.inventory 4 mutton 25
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=27}] run replaceitem entity @s slot.inventory 4 mutton 26
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=28}] run replaceitem entity @s slot.inventory 4 mutton 27
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=29}] run replaceitem entity @s slot.inventory 4 mutton 28
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=30}] run replaceitem entity @s slot.inventory 4 mutton 29
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=31}] run replaceitem entity @s slot.inventory 4 mutton 30
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=32}] run replaceitem entity @s slot.inventory 4 mutton 31
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=33}] run replaceitem entity @s slot.inventory 4 mutton 32
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=34}] run replaceitem entity @s slot.inventory 4 mutton 33
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=35}] run replaceitem entity @s slot.inventory 4 mutton 34
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=36}] run replaceitem entity @s slot.inventory 4 mutton 35
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=37}] run replaceitem entity @s slot.inventory 4 mutton 36
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=38}] run replaceitem entity @s slot.inventory 4 mutton 37
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=39}] run replaceitem entity @s slot.inventory 4 mutton 38
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=40}] run replaceitem entity @s slot.inventory 4 mutton 39
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=41}] run replaceitem entity @s slot.inventory 4 mutton 40
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=42}] run replaceitem entity @s slot.inventory 4 mutton 41
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=43}] run replaceitem entity @s slot.inventory 4 mutton 42
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=44}] run replaceitem entity @s slot.inventory 4 mutton 43
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=45}] run replaceitem entity @s slot.inventory 4 mutton 44
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=46}] run replaceitem entity @s slot.inventory 4 mutton 45
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=47}] run replaceitem entity @s slot.inventory 4 mutton 46
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=48}] run replaceitem entity @s slot.inventory 4 mutton 47
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=49}] run replaceitem entity @s slot.inventory 4 mutton 48
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=50}] run replaceitem entity @s slot.inventory 4 mutton 49
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=51}] run replaceitem entity @s slot.inventory 4 mutton 50
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=52}] run replaceitem entity @s slot.inventory 4 mutton 51
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=53}] run replaceitem entity @s slot.inventory 4 mutton 52
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=54}] run replaceitem entity @s slot.inventory 4 mutton 53
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=55}] run replaceitem entity @s slot.inventory 4 mutton 54
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=56}] run replaceitem entity @s slot.inventory 4 mutton 55
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=57}] run replaceitem entity @s slot.inventory 4 mutton 56
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=58}] run replaceitem entity @s slot.inventory 4 mutton 57
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=59}] run replaceitem entity @s slot.inventory 4 mutton 58
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=60}] run replaceitem entity @s slot.inventory 4 mutton 59
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=61}] run replaceitem entity @s slot.inventory 4 mutton 60
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=62}] run replaceitem entity @s slot.inventory 4 mutton 61
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=63}] run replaceitem entity @s slot.inventory 4 mutton 62
execute at @s if entity @s[hasitem={item=mutton,location=slot.inventory,slot=4,quantity=64}] run replaceitem entity @s slot.inventory 4 mutton 63

execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=1}] run replaceitem entity @s slot.inventory 4 air
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=2}] run replaceitem entity @s slot.inventory 4 rabbit 1
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=3}] run replaceitem entity @s slot.inventory 4 rabbit 2
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=4}] run replaceitem entity @s slot.inventory 4 rabbit 3
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=5}] run replaceitem entity @s slot.inventory 4 rabbit 4
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=6}] run replaceitem entity @s slot.inventory 4 rabbit 5
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=7}] run replaceitem entity @s slot.inventory 4 rabbit 6
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=8}] run replaceitem entity @s slot.inventory 4 rabbit 7
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=9}] run replaceitem entity @s slot.inventory 4 rabbit 8
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=10}] run replaceitem entity @s slot.inventory 4 rabbit 9
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=11}] run replaceitem entity @s slot.inventory 4 rabbit 10
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=12}] run replaceitem entity @s slot.inventory 4 rabbit 11
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=13}] run replaceitem entity @s slot.inventory 4 rabbit 12
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=14}] run replaceitem entity @s slot.inventory 4 rabbit 13
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=15}] run replaceitem entity @s slot.inventory 4 rabbit 14
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=16}] run replaceitem entity @s slot.inventory 4 rabbit 15
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=17}] run replaceitem entity @s slot.inventory 4 rabbit 16
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=18}] run replaceitem entity @s slot.inventory 4 rabbit 17
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=19}] run replaceitem entity @s slot.inventory 4 rabbit 18
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=20}] run replaceitem entity @s slot.inventory 4 rabbit 19
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=21}] run replaceitem entity @s slot.inventory 4 rabbit 20
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=22}] run replaceitem entity @s slot.inventory 4 rabbit 21
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=23}] run replaceitem entity @s slot.inventory 4 rabbit 22
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=24}] run replaceitem entity @s slot.inventory 4 rabbit 23
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=25}] run replaceitem entity @s slot.inventory 4 rabbit 24
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=26}] run replaceitem entity @s slot.inventory 4 rabbit 25
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=27}] run replaceitem entity @s slot.inventory 4 rabbit 26
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=28}] run replaceitem entity @s slot.inventory 4 rabbit 27
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=29}] run replaceitem entity @s slot.inventory 4 rabbit 28
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=30}] run replaceitem entity @s slot.inventory 4 rabbit 29
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=31}] run replaceitem entity @s slot.inventory 4 rabbit 30
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=32}] run replaceitem entity @s slot.inventory 4 rabbit 31
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=33}] run replaceitem entity @s slot.inventory 4 rabbit 32
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=34}] run replaceitem entity @s slot.inventory 4 rabbit 33
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=35}] run replaceitem entity @s slot.inventory 4 rabbit 34
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=36}] run replaceitem entity @s slot.inventory 4 rabbit 35
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=37}] run replaceitem entity @s slot.inventory 4 rabbit 36
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=38}] run replaceitem entity @s slot.inventory 4 rabbit 37
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=39}] run replaceitem entity @s slot.inventory 4 rabbit 38
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=40}] run replaceitem entity @s slot.inventory 4 rabbit 39
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=41}] run replaceitem entity @s slot.inventory 4 rabbit 40
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=42}] run replaceitem entity @s slot.inventory 4 rabbit 41
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=43}] run replaceitem entity @s slot.inventory 4 rabbit 42
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=44}] run replaceitem entity @s slot.inventory 4 rabbit 43
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=45}] run replaceitem entity @s slot.inventory 4 rabbit 44
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=46}] run replaceitem entity @s slot.inventory 4 rabbit 45
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=47}] run replaceitem entity @s slot.inventory 4 rabbit 46
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=48}] run replaceitem entity @s slot.inventory 4 rabbit 47
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=49}] run replaceitem entity @s slot.inventory 4 rabbit 48
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=50}] run replaceitem entity @s slot.inventory 4 rabbit 49
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=51}] run replaceitem entity @s slot.inventory 4 rabbit 50
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=52}] run replaceitem entity @s slot.inventory 4 rabbit 51
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=53}] run replaceitem entity @s slot.inventory 4 rabbit 52
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=54}] run replaceitem entity @s slot.inventory 4 rabbit 53
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=55}] run replaceitem entity @s slot.inventory 4 rabbit 54
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=56}] run replaceitem entity @s slot.inventory 4 rabbit 55
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=57}] run replaceitem entity @s slot.inventory 4 rabbit 56
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=58}] run replaceitem entity @s slot.inventory 4 rabbit 57
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=59}] run replaceitem entity @s slot.inventory 4 rabbit 58
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=60}] run replaceitem entity @s slot.inventory 4 rabbit 59
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=61}] run replaceitem entity @s slot.inventory 4 rabbit 60
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=62}] run replaceitem entity @s slot.inventory 4 rabbit 61
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=63}] run replaceitem entity @s slot.inventory 4 rabbit 62
execute at @s if entity @s[hasitem={item=rabbit,location=slot.inventory,slot=4,quantity=64}] run replaceitem entity @s slot.inventory 4 rabbit 63

execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=1}] run replaceitem entity @s slot.inventory 4 air
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=2}] run replaceitem entity @s slot.inventory 4 cod 1
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=3}] run replaceitem entity @s slot.inventory 4 cod 2
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=4}] run replaceitem entity @s slot.inventory 4 cod 3
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=5}] run replaceitem entity @s slot.inventory 4 cod 4
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=6}] run replaceitem entity @s slot.inventory 4 cod 5
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=7}] run replaceitem entity @s slot.inventory 4 cod 6
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=8}] run replaceitem entity @s slot.inventory 4 cod 7
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=9}] run replaceitem entity @s slot.inventory 4 cod 8
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=10}] run replaceitem entity @s slot.inventory 4 cod 9
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=11}] run replaceitem entity @s slot.inventory 4 cod 10
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=12}] run replaceitem entity @s slot.inventory 4 cod 11
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=13}] run replaceitem entity @s slot.inventory 4 cod 12
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=14}] run replaceitem entity @s slot.inventory 4 cod 13
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=15}] run replaceitem entity @s slot.inventory 4 cod 14
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=16}] run replaceitem entity @s slot.inventory 4 cod 15
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=17}] run replaceitem entity @s slot.inventory 4 cod 16
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=18}] run replaceitem entity @s slot.inventory 4 cod 17
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=19}] run replaceitem entity @s slot.inventory 4 cod 18
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=20}] run replaceitem entity @s slot.inventory 4 cod 19
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=21}] run replaceitem entity @s slot.inventory 4 cod 20
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=22}] run replaceitem entity @s slot.inventory 4 cod 21
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=23}] run replaceitem entity @s slot.inventory 4 cod 22
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=24}] run replaceitem entity @s slot.inventory 4 cod 23
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=25}] run replaceitem entity @s slot.inventory 4 cod 24
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=26}] run replaceitem entity @s slot.inventory 4 cod 25
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=27}] run replaceitem entity @s slot.inventory 4 cod 26
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=28}] run replaceitem entity @s slot.inventory 4 cod 27
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=29}] run replaceitem entity @s slot.inventory 4 cod 28
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=30}] run replaceitem entity @s slot.inventory 4 cod 29
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=31}] run replaceitem entity @s slot.inventory 4 cod 30
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=32}] run replaceitem entity @s slot.inventory 4 cod 31
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=33}] run replaceitem entity @s slot.inventory 4 cod 32
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=34}] run replaceitem entity @s slot.inventory 4 cod 33
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=35}] run replaceitem entity @s slot.inventory 4 cod 34
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=36}] run replaceitem entity @s slot.inventory 4 cod 35
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=37}] run replaceitem entity @s slot.inventory 4 cod 36
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=38}] run replaceitem entity @s slot.inventory 4 cod 37
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=39}] run replaceitem entity @s slot.inventory 4 cod 38
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=40}] run replaceitem entity @s slot.inventory 4 cod 39
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=41}] run replaceitem entity @s slot.inventory 4 cod 40
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=42}] run replaceitem entity @s slot.inventory 4 cod 41
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=43}] run replaceitem entity @s slot.inventory 4 cod 42
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=44}] run replaceitem entity @s slot.inventory 4 cod 43
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=45}] run replaceitem entity @s slot.inventory 4 cod 44
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=46}] run replaceitem entity @s slot.inventory 4 cod 45
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=47}] run replaceitem entity @s slot.inventory 4 cod 46
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=48}] run replaceitem entity @s slot.inventory 4 cod 47
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=49}] run replaceitem entity @s slot.inventory 4 cod 48
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=50}] run replaceitem entity @s slot.inventory 4 cod 49
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=51}] run replaceitem entity @s slot.inventory 4 cod 50
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=52}] run replaceitem entity @s slot.inventory 4 cod 51
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=53}] run replaceitem entity @s slot.inventory 4 cod 52
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=54}] run replaceitem entity @s slot.inventory 4 cod 53
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=55}] run replaceitem entity @s slot.inventory 4 cod 54
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=56}] run replaceitem entity @s slot.inventory 4 cod 55
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=57}] run replaceitem entity @s slot.inventory 4 cod 56
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=58}] run replaceitem entity @s slot.inventory 4 cod 57
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=59}] run replaceitem entity @s slot.inventory 4 cod 58
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=60}] run replaceitem entity @s slot.inventory 4 cod 59
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=61}] run replaceitem entity @s slot.inventory 4 cod 60
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=62}] run replaceitem entity @s slot.inventory 4 cod 61
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=63}] run replaceitem entity @s slot.inventory 4 cod 62
execute at @s if entity @s[hasitem={item=cod,location=slot.inventory,slot=4,quantity=64}] run replaceitem entity @s slot.inventory 4 cod 63

execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=1}] run replaceitem entity @s slot.inventory 4 air
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=2}] run replaceitem entity @s slot.inventory 4 salmon 1
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=3}] run replaceitem entity @s slot.inventory 4 salmon 2
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=4}] run replaceitem entity @s slot.inventory 4 salmon 3
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=5}] run replaceitem entity @s slot.inventory 4 salmon 4
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=6}] run replaceitem entity @s slot.inventory 4 salmon 5
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=7}] run replaceitem entity @s slot.inventory 4 salmon 6
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=8}] run replaceitem entity @s slot.inventory 4 salmon 7
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=9}] run replaceitem entity @s slot.inventory 4 salmon 8
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=10}] run replaceitem entity @s slot.inventory 4 salmon 9
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=11}] run replaceitem entity @s slot.inventory 4 salmon 10
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=12}] run replaceitem entity @s slot.inventory 4 salmon 11
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=13}] run replaceitem entity @s slot.inventory 4 salmon 12
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=14}] run replaceitem entity @s slot.inventory 4 salmon 13
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=15}] run replaceitem entity @s slot.inventory 4 salmon 14
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=16}] run replaceitem entity @s slot.inventory 4 salmon 15
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=17}] run replaceitem entity @s slot.inventory 4 salmon 16
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=18}] run replaceitem entity @s slot.inventory 4 salmon 17
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=19}] run replaceitem entity @s slot.inventory 4 salmon 18
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=20}] run replaceitem entity @s slot.inventory 4 salmon 19
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=21}] run replaceitem entity @s slot.inventory 4 salmon 20
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=22}] run replaceitem entity @s slot.inventory 4 salmon 21
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=23}] run replaceitem entity @s slot.inventory 4 salmon 22
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=24}] run replaceitem entity @s slot.inventory 4 salmon 23
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=25}] run replaceitem entity @s slot.inventory 4 salmon 24
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=26}] run replaceitem entity @s slot.inventory 4 salmon 25
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=27}] run replaceitem entity @s slot.inventory 4 salmon 26
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=28}] run replaceitem entity @s slot.inventory 4 salmon 27
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=29}] run replaceitem entity @s slot.inventory 4 salmon 28
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=30}] run replaceitem entity @s slot.inventory 4 salmon 29
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=31}] run replaceitem entity @s slot.inventory 4 salmon 30
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=32}] run replaceitem entity @s slot.inventory 4 salmon 31
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=33}] run replaceitem entity @s slot.inventory 4 salmon 32
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=34}] run replaceitem entity @s slot.inventory 4 salmon 33
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=35}] run replaceitem entity @s slot.inventory 4 salmon 34
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=36}] run replaceitem entity @s slot.inventory 4 salmon 35
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=37}] run replaceitem entity @s slot.inventory 4 salmon 36
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=38}] run replaceitem entity @s slot.inventory 4 salmon 37
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=39}] run replaceitem entity @s slot.inventory 4 salmon 38
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=40}] run replaceitem entity @s slot.inventory 4 salmon 39
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=41}] run replaceitem entity @s slot.inventory 4 salmon 40
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=42}] run replaceitem entity @s slot.inventory 4 salmon 41
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=43}] run replaceitem entity @s slot.inventory 4 salmon 42
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=44}] run replaceitem entity @s slot.inventory 4 salmon 43
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=45}] run replaceitem entity @s slot.inventory 4 salmon 44
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=46}] run replaceitem entity @s slot.inventory 4 salmon 45
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=47}] run replaceitem entity @s slot.inventory 4 salmon 46
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=48}] run replaceitem entity @s slot.inventory 4 salmon 47
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=49}] run replaceitem entity @s slot.inventory 4 salmon 48
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=50}] run replaceitem entity @s slot.inventory 4 salmon 49
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=51}] run replaceitem entity @s slot.inventory 4 salmon 50
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=52}] run replaceitem entity @s slot.inventory 4 salmon 51
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=53}] run replaceitem entity @s slot.inventory 4 salmon 52
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=54}] run replaceitem entity @s slot.inventory 4 salmon 53
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=55}] run replaceitem entity @s slot.inventory 4 salmon 54
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=56}] run replaceitem entity @s slot.inventory 4 salmon 55
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=57}] run replaceitem entity @s slot.inventory 4 salmon 56
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=58}] run replaceitem entity @s slot.inventory 4 salmon 57
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=59}] run replaceitem entity @s slot.inventory 4 salmon 58
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=60}] run replaceitem entity @s slot.inventory 4 salmon 59
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=61}] run replaceitem entity @s slot.inventory 4 salmon 60
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=62}] run replaceitem entity @s slot.inventory 4 salmon 61
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=63}] run replaceitem entity @s slot.inventory 4 salmon 62
execute at @s if entity @s[hasitem={item=salmon,location=slot.inventory,slot=4,quantity=64}] run replaceitem entity @s slot.inventory 4 salmon 63